# Compose V2: no top-level version key
services:
  db:
    image: postgres:16-alpine
    container_name: orga5_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./backend
    container_name: orga5_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/postgres}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orga5_web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      VITE_API_BASE_URL: http://localhost:8000

volumes:
  db_data:
