version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: orga5_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orga5}
      POSTGRES_USER: ${POSTGRES_USER:-orga}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orga}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    container_name: orga5_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://orga:orga@db:5432/orga5}
      UVICORN_PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: ./frontend
    container_name: orga5_web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      VITE_API_BASE_URL: http://localhost:8000

volumes:
  db_data:
